### ISSUE TITLE
super read only does not prevent DROP TRIGGER

### ISSUE THREAD

**Issue by laurynas-biveinis** [facebookarchive/webscalesql-5.6#10]
Super read only patch at https://github.com/webscalesql/webscalesql-5.6/commit/73fe122dd4b7f1a0fa79f338a7a0c4e5809389e2 does not enforce the option on DROP TRIGGER, that is, a SUPER user can drop them regardless of the option value.

Fix is easy, the SRO handling pattern has to be added mysql_create_or_drop_trigger.

While at that, the MTR in the patch is missing some SRO tests implemented in the code: for multi-table update, START TRANSACTION READ WRITE, and CREATE TRIGGER.

**Comment by steaphan-fb-com** [comment]
Interesting.  I'd be happy to review a patch that improves all of these things.  :)

**Comment by laurynas-biveinis** [comment]
https://github.com/webscalesql/webscalesql-5.6/pull/11

**Comment by steaphan-fb-com** [comment]
I've confirmed that #11 does solve this issue.  We'll track the progress of applying that patch in that pull request from here on.

Thanks!
