### ISSUE TITLE
mysql_com.h uses C_MODE_START/C_MODE_END without including a definition

### ISSUE THREAD

**Issue by fredemmott** [facebookarchive/webscalesql-5.6#13]
- This is provided by my_global.h - however, mysql_com.h doesn't include it
- Including my_global.h isn't required with standard MySQL, so shouldn't be here
- my_global.h isn't a friendly thing to include in user code - eg redefining int32. This conflicts with common libraries eg glog/gflags

Replacing C_MODE_START with with:

```
#ifdef __cplusplus
extern "C" {
#endif
```

and C_MODE_END with:

```
#ifdef __cplusplus
} // extern "C"
#endif
```

fixes the problem, but is duplication.

**Comment by steaphangreene** [comment]
This proposed diff should fix this:

https://reviews.facebook.net/D32811

**Comment by steaphan-fb-com** [comment]
This fix has been pushed.  Let us know if this doesn't resolve this issue.
