### ISSUE TITLE
Gitignore file very incomplete

### ISSUE THREAD

**Issue by fredemmott** [facebookarchive/webscalesql-5.6#16]
- out of tree builds don't appear to be supported (can't find mysql_version.h)
- makesfiles, cmake files, .o, .a, .... everything shows up in 'git status' afterwards

**Comment by steaphangreene** [comment]
Out of tree builds are the norm, the upstream build system is quite unfriendly to in-tree building.

I have not seen any build problem related to "mysql_version.h".  Can you send more details of exactly what you are running, and exactly what you are seeing?

**Comment by steaphan-fb-com** [comment]
Please open a new issue with full details if out-of-tree builds are not working for you.
