### ISSUE TITLE
mysqld doesn't completely shutdown

### ISSUE THREAD

**Issue by maykov** [facebookarchive/webscalesql-5.6#21]
Run
$/data/users/maykov/mysql/build-5.6-Debug/sql/mysqld --help --verbose

You will see:

Error in my_thread_global_end(): 1 threads didn't exit

I reproed this in Myrocks branch, but Just told me this also exists in Webscale. Justin was able to bisect this problem to https://github.com/webscalesql/webscalesql-5.6/commit/a7ed5a71a17c0982288f9adf45ca4eac0fc0fa78

**Comment by inaam-rana** [comment]
Proposed fix: https://reviews.facebook.net/D37581

**Comment by inaam-rana** [comment]
pushed
