### ISSUE TITLE
innodb_doublewrite may leave a dangling mysqld process with locked ibdata

### ISSUE THREAD

**Issue by laurynas-biveinis** [facebookarchive/webscalesql-5.6#26]
Tested with 5.6.24 on Ubuntu 15.04:

$ ./mtr --debug-server innodb_doublewrite
...
innodb.innodb_doublewrite                [ fail ]  Found warnings/errors in server log file!
        Test ended at 2015-08-04 14:34:18
line
2015-08-04 14:34:16 16651 [ERROR] InnoDB: Unable to lock ./ibdata1, error: 11
^ Found warnings in /home/laurynas/obj-webscalesql-5.6.24-debug/mysql-test/var/log/mysqld.1.err
ok
...

$ ps aux | grep [m]ysqld
laurynas 16627  0.5  1.9 1213860 39248 pts/1   Sl   14:33   0:01 /home/laurynas/obj-webscalesql-5.6.24-debug/sql/mysqld-debug --defaults-group-suffix=.1 --defaults-file=/home/laurynas/obj-webscalesql-5.6.24-debug/mysql-test/var/my.cnf --log_error=/home/laurynas/obj-webscalesql-5.6.24-debug/mysql-test/var/tmp/innodb_corrupt_doublewrite-1.log

The --log_error part shows this to be a mysqld started by innodb_corrupt_doublewrite_pages.py. Inspecting the log and attaching with gdb shows the server waiting for incoming connections. But it has clobbered the datadir, causing subsequent tests in the same MTR run to fail.

**Comment by lth** [comment]
I was unable to reproduce this problem on my local setup. Are you still hitting this problem? Is there any additional information that you can give about your setup?

Just from reading the code, the mysqld process spawned by innodb_corrupt_doublewrite_pages.py should have been terminated after 30 seconds. If the process is not finished, it should at least be shutting down, not accepting incoming connections.

**Comment by laurynas-biveinis** [comment]
It's still there.
Ubuntu 15.04 (VirtualBox 5.0.8 on Mac OS X host).

$ git log -1 --oneline
ed79f11 Fixed MTR failure main.events_1.test
...
$ cmake ../mysql-server/ -DBUILD_CONFIG=mysql_release -DBUILD_TYPE=Debug -DWITH_SSL=system
...
$ ./mtr innodb_doublewrite

```
Logging: /home/laurynas/mysql-server/mysql-test/mysql-test-run.pl  innodb_doublewrite
2015-11-10 09:57:55 0 [Note] /home/laurynas/obj-webscalesql-5.6.26-debug/sql/mysqld (mysqld 5.6.26) starting as process 5894 ...
2015-11-10 09:57:55 5894 [Note] Plugin 'FEDERATED' is disabled.
2015-11-10 09:57:55 5894 [Note] Binlog end
2015-11-10 09:57:55 5894 [Note] Shutting down plugin 'CSV'
2015-11-10 09:57:55 5894 [Note] Shutting down plugin 'MyISAM'
MySQL Version 5.6.26
Checking supported features...
 - SSL connections supported
Tests will be run in sync (default) client mode
Collecting tests...
Removing old var directory...
Creating var directory '/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var'...
Installing system database...

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
innodb.innodb_doublewrite                [ fail ]  Found warnings/errors in server log file!
        Test ended at 2015-11-10 09:58:45
line
2015-11-10 10:58:43 6016 [ERROR] InnoDB: Unable to lock ./ibdata1, error: 11
^ Found warnings in /home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/log/mysqld.1.err
ok

 - saving '/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/log/innodb.innodb_doublewrite/' to '/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/log/innodb.innodb_doublewrite/'
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 50 seconds executing testcases
mysql-test-run: WARNING: Got errors/warnings while running tests, please examine '/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/log/warnings' for details.

Completed: Failed 1/1 tests, 0.00% were successful.

Failing test(s): innodb.innodb_doublewrite

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

mysql-test-run: *** ERROR: there were failing test cases
```

laurynas@ubuntu-vivid-1:~/obj-webscalesql-5.6.26-debug/mysql-test$ ps aux | grep [m]ysqld

```
laurynas  5992  0.8  0.8 684004 33192 pts/0    Sl   09:58   0:00 /home/laurynas/obj-webscalesql-5.6.26-debug/sql/mysqld --defaults-group-suffix=.1 --defaults-file=/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/my.cnf --log_error=/home/laurynas/obj-webscalesql-5.6.26-debug/mysql-test/var/tmp/innodb_corrupt_doublewrite-1.log
```

**Comment by lth** [comment]
Thanks, I was able to reproduce it. I'll have a fix out soon.
