### ISSUE TITLE
webscalesql-5.6 Truck Factor

### ISSUE THREAD

**Issue by gavelino** [facebookarchive/webscalesql-5.6#30]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **webscalesql-5.6** and obtained a value of **11**.

The developers responsible for this TF are:

Murthy Narkedimilli - author of 21% of the files
magnus@neptunus.(none) - author of 16% of the files
Bernd Ocklin - author of 13% of the files
bk@work.mysql.com - author of 8% of the files
Kent Boortz - author of 7% of the files
Jimmy Yang - author of 6% of the files
Marc Alff - author of 5% of the files
Jonas Oreland - author of 4% of the files
Satya B - author of 3% of the files
jonas@perch.ndb.mysql.com - author of 3% of the files
monty@donna.mysql.com - author of 3% of the files

To validate our results, we would like to ask **webscalesql-5.6** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **webscalesql-5.6**?

(b) Do you agree that **webscalesql-5.6** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **webscalesql-5.6** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by jeremycole** [comment]
Not relevant to this project.
