### ISSUE TITLE
cmake version 2.8.7 Compile error,need for helps,ths

### ISSUE THREAD

**Issue by vcdog** [facebookarchive/webscalesql-5.6#4]
Linking C static library libmysys.a
[ 17%] Built target mysys
Scanning dependencies of target dbug
[ 17%] Building C object dbug/CMakeFiles/dbug.dir/dbug.c.o
Linking C static library libdbug.a
[ 17%] Built target dbug
Scanning dependencies of target mysys_ssl
[ 18%] Building CXX object mysys_ssl/CMakeFiles/mysys_ssl.dir/crypt_genhash_impl.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: **\* [mysys_ssl/CMakeFiles/mysys_ssl.dir/crypt_genhash_impl.cc.o] Error 1
make[1]: **\* [mysys_ssl/CMakeFiles/mysys_ssl.dir/all] Error 2
make: **\* [all] Error 2

**Comment by mdcallag** [comment]
This bug report is seriously lacking in detail.

**Comment by vcdog** [comment]
cmake -DCMAKE_INSTALL_PREFIX=/data/webscalesoft -DMYSQL_UNIX_ADDR=/data/webscalesoft/mysql.sock -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DEXTRA_CHARSETS=all -DWITH_INNOBASE_STORAGE_ENGINE=1 -DWITH_MYISAM_STORAGE_ENGINE=1 -DWITH_ARCHIVE_STORAGE_ENGINE=1 -DWITH_BLACKHOLE_STORAGE_ENGINE=1 -DMYSQL_DATADIR=/data/webscaledb -DMYSQL_TCP_PORT=3308 -DENABLE_DOWNLOADS=1
-- Running cmake version 2.8.10.2
-- MySQL 5.6.17
-- Packaging as: mysql-5.6.17-Linux-x86_64
-- HAVE_VISIBILITY_HIDDEN
-- HAVE_VISIBILITY_HIDDEN
-- HAVE_VISIBILITY_HIDDEN
-- Using cmake version 2.8.10.2
-- Not building NDB
-- Library mysqlclient depends on OSLIBS -lpthread;m;rt;dl
-- GMOCK_SOURCE_DIR:/data/dba_tools/webscalesql-5.6-webscalesql-5.6.17/source_downloads/gmock-1.6.0
-- Performing Test HAVE_NO_NULL
-- Performing Test HAVE_NO_NULL - Failed
-- Performing Test HAVE_NO_UNUSED_TYPEDEFS
-- Performing Test HAVE_NO_UNUSED_TYPEDEFS - Failed
-- GTEST_LIBRARIES:gmock;gtest
-- Library mysqlserver depends on OSLIBS -lpthread;m;rt;crypt;dl;aio
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

```
ENABLE_DOWNLOADS
```

**Comment by vcdog** [comment]
Following the installation environment：
CentOS release 6.4 (Final)  core version:2.6.32-358.el6.x86_64
cmake version 2.8.7 
bison version 2.5
m4-1.4.16
webscalesql-5.6-webscalesql-5.6.17
gcc-4.4.7-3.el6.x86_64
readline-6.0-4.el6.x86_64
readline-devel-6.0-3.el6.x86_64
ncurses-devel-5.7-3.20090208.el6.x86_64

**Comment by vcdog** [comment]
Q: Is building WebScaleSQL just like building MySQL?
 We have made a few changes so far, that you may need to know.
 Building WebScaleSQL requires at least GCC version 4.7, or an equivalent CLang version.
 To make a WebScaleSQL debug build, use only -DCMAKE_BUILD_TYPE=Debug not -DWITH_DEBUG.
 WebScaleSQL requires readline-dev or libreadline-dev (depending on the Linux distribution) to build.
 WebScaleSQL does not currently maintain compatibility for anything except GNU/Linux x86_64.
 If you make code changes, be aware that we build as C++11 and C99.

**Comment by mdcallag** [comment]
much better

**Comment by vcdog** [comment]
Is it because my gcc version is too low??

**Comment by mdcallag** [comment]
Probably. I don't hack on it anymore but there was desire to use features only available in the latest C++ standard and latest g++ versions. This would be a good thing to explain in the FAQ.

**Comment by pivanof** [comment]
As you correctly cited the FAQ item, you need to have gcc 4.7 or higher to build WebScaleSQL. gcc 4.4 won't work.

**Comment by vcdog** [comment]
My problem has been resolved,ths  a lot.operation Follows

$ cd /etc/yum.repos.d/
$ wget  http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo
$ yum repolist
$ yum install devtoolset-1.1
$ scl enable devtoolset-1.1 bash
$ rm CMakeCache.txt 
$ cmake -DCMAKE_INSTALL_PREFIX=/data/webscalesoft \
-DMYSQL_UNIX_ADDR=/data/webscalesoft/mysql.sock \
-DDEFAULT_CHARSET=utf8 \
-DDEFAULT_COLLATION=utf8_general_ci \
-DEXTRA_CHARSETS=all \
-DWITH_INNOBASE_STORAGE_ENGINE=1 \
-DWITH_MYISAM_STORAGE_ENGINE=1 \
-DWITH_ARCHIVE_STORAGE_ENGINE=1 \
-DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
-DMYSQL_DATADIR=/data/webscaledb \
-DMYSQL_TCP_PORT=3308 \
-DENABLE_DOWNLOADS=1
$make && make install

I hope it  help to others.Thanks.

**Comment by royzhao** [comment]
I also have some question，but I update my gcc to 4.8，it‘s has error that

 ‘cc1plus: error: unrecognized command line option "-std=c++11"’

finally，I found the environment path is wrong，I used the gcc4.4 version`s cc1plus，then , I delete the old cc1plus,I wish system auto use new version,however,system told me cc1puls not found!!
then,I used cmd

"yum remove gcc"

then complie pass!
I hope it help to others too .Thanks
