### ISSUE TITLE
I can't see the webscalesql engine from database??why??

### ISSUE THREAD

**Issue by vcdog** [facebookarchive/webscalesql-5.6#6]
I use I use the following parameters to compile my webscalesql-5.6.17:
# cmake -DCMAKE_INSTALL_PREFIX=/data/webscalesoft \

-DMYSQL_UNIX_ADDR=/data/webscalesoft/mysql.sock \
-DDEFAULT_CHARSET=utf8 \
-DDEFAULT_COLLATION=utf8_general_ci \
-DEXTRA_CHARSETS=all \
-DWITH_INNOBASE_STORAGE_ENGINE=1 \
-DWITH_MYISAM_STORAGE_ENGINE=1 \
-DWITH_ARCHIVE_STORAGE_ENGINE=1 \
-DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
-DWITH_FEDERATED_STORAGE_ENGINE=1\
-DWITH_PARTITION_STORAGE_ENGINE=1\
-DWITH_PERFSCHEMA_STORAGE_ENGINE=1\
-DWITH_WEBSCALESQL_STORAGE_ENGINE=1\
-DMYSQL_DATADIR=/data/webscaledb \
-DMYSQL_TCP_PORT=3307 \
-DENABLE_DOWNLOADS=1\
-DCMAKE_BUILD_TYPE=Debug
# make && make install
# mysql -uroot -p -P 3307 -S /data/webscalesoft/mysql.sock

Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.6.17-log Source distribution

Copyright (c) 2000, 2012, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

mysql> show engines;
+------------+---------+----------------------------------------------------------------+--------------+------+------------+
| Engine     | Support | Comment                                                        | Transactions | XA   | Savepoints |
+------------+---------+----------------------------------------------------------------+--------------+------+------------+
| MRG_MYISAM | YES     | Collection of identical MyISAM tables                          | NO           | NO   | NO         |
| InnoDB     | DEFAULT | Supports transactions, row-level locking, and foreign keys     | YES          | YES  | YES        |
| MyISAM     | YES     | MyISAM storage engine                                          | NO           | NO   | NO         |
| BLACKHOLE  | YES     | /dev/null storage engine (anything you write to it disappears) | NO           | NO   | NO         |
| CSV        | YES     | CSV storage engine                                             | NO           | NO   | NO         |
| FEDERATED  | NO      | Federated MySQL storage engine                                 | NULL         | NULL | NULL       |
| ARCHIVE    | YES     | Archive storage engine                                         | NO           | NO   | NO         |
| MEMORY     | YES     | Hash based, stored in memory, useful for temporary tables      | NO           | NO   | NO         |
+------------+---------+----------------------------------------------------------------+--------------+------+------------+
8 rows in set (0.00 sec)

mysql> 

but I can't still see the webscalesql engine?? I want to kown why the wescalesql engine is    Appear??

**Comment by vcdog** [comment]
And the mysql－5.6 default PERFORMANCE_SCHEMA engine is not  Appear.But  when I compiled it,
I have Specified 
-DWITH_PERFSCHEMA_STORAGE_ENGINE=1\
-DWITH_WEBSCALESQL_STORAGE_ENGINE=1\
so I Do not understand  why?? I hope reply?Ths!

**Comment by pivanof** [comment]
There is no engine named "webscalesql", we didn't add anything like that. And compilation of performance_schema is disabled by default in our sources.

**Comment by steaphan-fb-com** [comment]
Correct.  WebScaleSQL is a branch of MySQL, not a storage engine within it.

And, PerfSchema is disabled by default, but running the initial cmake with -DWITH_PERFSCHEMA_STORAGE_ENGINE=1, and doing a clean rebuild, should enable it again.
