### ISSUE TITLE
A thread running SHOW PROCESSLIST shows Status "cleaning up" rather than "init" (mysql 5.6)

### ISSUE THREAD

**Issue by sjmudd** [facebookarchive/webscalesql-5.6#7]
While maybe not an issue I notice that if I run SHOW PROCESSLIST the thread that runs the query shows it is in State "Cleaning up". MySQL shows "init".  If this is known and expected that's fine: it would be good to know that.

```
root@webscalesql56 [(none)]> pager grep root
PAGER set to 'grep root'
root@webscalesql56 [(none)]> show processlist;
| 2644 | root        | localhost                                     | NULL               | Query   |    0 | cleaning up                      | show processlist                                                                                     |
4 rows in set (0.00 sec)
```

```
root@mysql56 [(none)]> pager grep root
PAGER set to 'grep root'
root@mysql56 [(none)]> show processlist;
| 28256365 | root            | localhost                                  | NULL  | Query            |      0 | init                                                                  | show processlist                                                                                     |
208 rows in set (0.00 sec)
```

Seen on a box running CentOS 6, using my rpm build script: https://github.com/sjmudd/webscalesql-rpm/, but all this does is package the source tree as a normal rpm.

```
$ rpm -q webscalesql-server
webscalesql-server-5.6-0.20140327.145247.rhel6.x86_64
```

**Comment by pivanof** [comment]
AFAIK this is just a race and if you run SHOW PROCESSLIST several times you'll be able to see different states different times. See https://github.com/webscalesql/webscalesql-5.6/commit/302ba4c82aa13ba56e914491fc2611e85d768532.

**Comment by steaphan-fb-com** [comment]
Yes, @pivanof, that's  correct.
